### PR TITLE
Patch build config with nexus credentials & changed to redhat image

### PR DESCRIPTION
**Pull request by sklingel**
ported jupyter notebook to same Redhat image that is used in ds-ml-service.
+ moved pip installations into docker build

### CODE REVIEW

**Comment by sklingel** [comment]
Actually I discovered some problems with the solution in https://github.com/opendevstack/ods-project-quickstarters/pull/204.
RUN pip install --upgrade pip && \
	    cd src \
	    if [[ ! -z ${nexusHost} ]]; then  \
	        pip install -i ${nexusHostWithBasicAuth}/repository/pypi-all/simple -r requirements.txt; \
	    else \
	        pip install -r requirements.txt; \
	    fi

1. the pip upgrade will definitely bypass nexus.
2. the nexus install will never be used, since `nexusHost` is not set in the Dockerfile, and will therefore be not set. Thus, nexus will by also bypassed.

Or did I got something wrong? @michaelsauter

**Comment by michaelsauter** [comment]
@sklingel Ha, good catch! The condition is wrong because it was changed last minute :( 

Do we even need to upgrade pip here?!

**Comment by tbugfinder** [comment]
IMHO, updating pip make sense - just review the list of fixes / changes.

**Comment by sklingel** [comment]
Because this effects some more Dockerfiles, I created a new PR #213, and close this one.

**Pull request closed without merging**
