### PR TITLE
polish be-docker-plain

### PR DESCRIPTION
**Pull request by tbugfinder**
Enhance be-docker-plain having a valid service running.

### CODE REVIEW

**Comment by clemensutschig** [comment]
Top.. thanks @tbugfinder

**Comment by metmajer** [comment]
@tbugfinder some feedback:

1) Do we really need to have a full NGINX installation in a plain docker quickstarter template? Users would have to clean up before they can start using it. I'd rather use your example in a README.md or a blog post so others can understand what to modify to arrive at an NGINX Docker image.
2) Using `ENTRYPOINT` won't let you override the container process or pass in additional options. `CMD` is usually preferred (see my comments above). Also, I'd rather not have an extra `entrypoint.sh` file to carry around unless really needed (which it is not for such simple examples). You should use the `ENTRYPOINT` or `CMD`'s exec form to run multiple commands in succession directly and without the file indirection like so:

```
CMD ["sh", "-c", "cmd1 && cmd2"]
```

**Comment by clemensutschig** [comment]
What about running just 'nc' and echoing hellow.. done

**Comment by metmajer** [comment]
An approach that's often seen is to simply sleep in a loop. Here is a fully working example:

```
FROM alpine:latest

CMD ["/bin/sh", "-c", "while true; do sleep 1d; done"]
```

Here, the `CMD` directive uses the exec form, which is the Docker recommended way. The exec form though does not execute a shell, but we need one to execute the loop.

**Comment by gerardcl** [comment]
I would really consider this https://github.com/opendevstack/ods-project-quickstarters/issues/260#issuecomment-510881603

**Comment by clemensutschig** [comment]
Status?

**Comment by metmajer** [comment]
@gerardcl I think that a security workflow could easily over-complicate things. Especially at the beginning of a project where you are still in an exploratory phase. Do you think that would be compatible? Also, personally, a security workflow decision doesn't have to block this issue moving forward.

@tbugfinder I prefer @clemensutschig's approach with `nc` since it overall:
1) shows how to install an artifact (`nc`) inside the Dockerfile
2) shows how to run a command with arguments in a (`CMD` please) exec form
3) lets the containerized process respond with a message so the user can verify that the deployment was successful using a simple HTTP request

**Comment by gerardcl** [comment]
@metmajer I fully agree on what you say and I believe it indeed follows the quickstarter purposes. My comment was more on the direction on implementing right workflows internally (and maybe expose them from an ODS point of view) so to keep that comment in mind...I also commented in the past that we could (since being only using openshift) stick to official provided images by RH, but I think that a DTR path is much more a better track! I see this as a self-managed artifact/dependency management tool (e.g.: nexus) with an enhanced "check" layer, isn't?

Following the proposals for keeping the docker alive and solve this issue we are in I agree on what you proposed. We could even load a message saying "Hello world" hehe

**Comment by gerardcl** [comment]
Hi again,

I was thinking and following your comments now, what about a Dockerfile like the following:

```Dockerfile
FROM alpine:latest

RUN apk add python3

RUN echo "Hello World" > index.html

EXPOSE 8080

USER 1001

CMD ["python3", "-m", "http.server", "8080"]
```

?

**Comment by clemensutschig** [comment]
For me still too complex... just 'nc' should do

gerardcl <notifications@github.com> schrieb am Sa., 20. Juli 2019, 17:30:

**Comment by gerardcl** [comment]
yep, I am also fine, indeed the goal is that the user just rewrites everything so even better if he/she does not need to also "remove" hehe
yep!

**Comment by michaelsauter** [comment]
I agree with @metmajer and @clemensutschig, please just use the simplest possible, and then let's get this merged.

**Comment by metmajer** [comment]
@tbugfinder note that an `echo "Hello World!" | nc -l 8080` will terminate after it has sent the response once. There should be an option `-k`, depending on the target OS, that keeps `nc` listening. This resource may help: https://superuser.com/questions/1008348/netcat-keep-listening-for-connection-in-debian.

**Comment by gerardcl** [comment]
@metmajer right! see https://github.com/opendevstack/ods-project-quickstarters/pull/264#issuecomment-511149132 
then there is consensus on the solution to provide for this Dockerfile:
```Dockerfile
# This is an example dummy Dockerfile
FROM alpine:latest

CMD ["nc", "-k", "-l", "127.0.0.1", "8080"]
```

**Comment by metmajer** [comment]
Hey @gerardcl and thanks for chiming in! Currently, your implementation wouldn't echo anything. For `nc` to emit `Hello World!`, we'd need the following in plain Bash (the `127.0.0.1` is optional):

```
echo Hello World! | nc -k -l 8080
```

In exec form, this would need to be written as `CMD ["/bin/sh",  "-c", "echo Hello World! | nc -k -l 8080"]` because of the pipe. What do you think?

**Comment by metmajer** [comment]
@gerardcl Because it's @tbugfinder's first contribution, I'd like him to finish this off. Hurry up, @tbugfinder and let me know if you need support :)

**Comment by gerardcl** [comment]
sure @metmajer :) but please test it before since I think it has an issue (not killing) when trying to kill the docker if doing the pipe

**Comment by tbugfinder** [comment]
Updated the CMD as requested.

**Comment by tbugfinder** [comment]
@clemensutschig I'm slightly confused where to edit CHANGELOG.md. Should a comment be added into `## [Unreleased]` ?

**Comment by tbugfinder** [comment]
Should ODS make use of https://github.com/teohm/git-chlog ?

**Comment by clemensutschig** [comment]
@tbugfinder correct

**Comment by tbugfinder** [comment]
This was tested successfully, indeed.

**Comment by tbugfinder** [comment]
removed WIP flag.

**Comment by michaelsauter** [comment]
@tbugfinder Cool! Thanks for the link to the changelog tool, did not know it. It would be really nice to have something like this. Right now though, our changelogs are based on issues, not pull requests ...

**Pull request merged**
