### PR TITLE
tightended rolebindings based on groups

### PR DESCRIPTION
**Pull request by clemensutschig**
proposal fix for #112  
heavily depending on opendevstack/ods-jenkins-shared-library#64

### CODE REVIEW

**Comment by clemensutschig** [comment]
@stephenkehoe FYI

**Comment by clemensutschig** [comment]
ok the trick now is to pass entitlement groups - that get the rights view / edit / admin .. and if they are not set everyone can view / edit ... - so we follow the original design ..

**Comment by michaelsauter** [comment]
@clemensutschig Should we still restrict the default to `view`? I would be in favour of that ...

**Comment by clemensutschig** [comment]
> @clemensutschig Should we still restrict the default to `view`? I would be in favour of that ...

it's there in case no entitlements passed - isnt that good enough?

**Pull request merged**
