### PR TITLE
Feature/dsi dvc data versioning pip nexus fix

### PR DESCRIPTION
**Pull request by sklingel**
This PR includes all issues mentioned in #209, #208 and closed PR #207, meaning:

* fixing all nexus builds using the right pip and trusted host
* moving Jupyter image to RHEL image
* including new Machine Learning Quickstarter functionality: dvc data versioning

### CODE REVIEW

**Comment by sklingel** [comment]
@clemensutschig, @michaelsauter, @gerardcl, I included all the mentioned issues in this PR

**Comment by gerardcl** [comment]
hi! This should also go to next minor release (next week), does it make sense?

**Comment by clemensutschig** [comment]
@michaelsauter - please incluse into 1.1

**Comment by clemensutschig** [comment]
Merge now.. 1.1 fixes

gerardcl <notifications@github.com> schrieb am Fr., 24. Mai 2019, 17:34:

**Pull request merged**
