### PR TITLE
Feature/dsi 2 first quickstarter implementation

### LINKED ISSUE #111: new quickstarter for Data Science Machine Learning services
This new quickstarter will provide CI/CD for ML training and prediction services usually required for Data Scientists working within a software development project/team.

First release will be based on Python programming language.

More features will be provided soon.

### PR DESCRIPTION
**Pull request by gerardcl**
closes #111

### CODE REVIEW

**Comment by clemensutschig** [comment]
Great work! One piece i am missing is the etl / airflow integration.. do you envision this separate?

**Comment by gerardcl** [comment]
Hi @clemensutschig , I think the goal is to keep both concepts separated. Anyway, it does not mean that with this implementation you cannot implement your own small ETL job, which, of course, can later on use an airflow instance...
But yes, I fully see an integration with airflow in the future...which will come for sure, at least I'll push for that, and as said already working on it...step by step!

**Comment by gerardcl** [comment]
by the way, @michaelsauter @clemensutschig shall we add this into 1.0.x once merged ?

**Comment by michaelsauter** [comment]
@gerardcl No, this is a feature, and therefore goes into 1.1.0.

**Pull request merged**
